### ISSUE TITLE
Always returns [GSI_LOGGER]: Missing required parameter: client_id.

### ISSUE THREAD

**Issue by noskap** [mpreziuso/ngx-one-tap#1]
I've tried parsing the client_id both inside the module:
  ```
NgxOneTapModule.config({ 
      client_id: '[REDACTED].apps.googleusercontent.com',
      cancel_on_tap_outside: false,
      auto_select: false,
      login_uri: 'http://localhost:4200/auth/login'
  }),
```
and also the init() function:
```
  this.onetap.init({
      client_id: '[REDACTED].apps.googleusercontent.com',
      context: 'signup',
      allowed_parent_origin: ['http://localhost:4200'],
  });
```
No matter what I try I always get the error: `[GSI_LOGGER]: Missing required parameter: client_id.`

**Comment by mpreziuso** [comment]
Hi @noskap,

Thanks for raising this issue, but unfortunately I'm unable to reproduce it.
I have the same setup in a test project:
```
NgxOneTapModule.config({
      client_id: environment.google.client_id,
      cancel_on_tap_outside: true,
      auto_select: false,
    }),
```
in my `auth.module.ts`

and 
```
  ngOnInit(): void {
    this.onetap.init({
      client_id: this.client_id,
      context: 'signin',
    });
  }
```
in a component.

**EDIT**
A step is missing in the documentation: you should also add `<ngx-one-tap></ngx-one-tap>` in your component HTML.

Are you able to provide a Stackblitz or similar?
